### ISSUE TITLE
PS4eop Error

### ISSUE THREAD

**Issue by Jackistheprogrammergod432** [Azerrs/PS4eop#6]
So i just got a error from the emulator trying to get Ghost of Tsushima running here is the error i got.
FEOP-0385784  = Missing license right?

**Comment by Azerrs** [comment]
> So i just got a error from the emulator trying to get Ghost of Tsushima running here is the error i got.
> FEOP-0385784 = Missing license right?

ETYW-473294 = Missing License, FEOP-0385784 is Missing Files. check the package file and dump the package file and then try to run it

**Comment by Jackistheprogrammergod432** [comment]
> > So i just got a error from the emulator trying to get Ghost of Tsushima running here is the error i got.
> > FEOP-0385784 = Missing license right?
> 
> ETYW-473294 = Missing License, FEOP-0385784 is Missing Files. check the package file and dump the package file and then try to run it

Yep got it working
