### ISSUE TITLE
PS4 Emulator error

### ISSUE THREAD

**Issue by Jackistheprogrammergod432** [Azerrs/PS4eop#7]
So I Popped in a disc game and it installed and launched but it crashed here is the codes it punched out.

CJNV-086558
XPWQ-927464
ETYZ-700432

It was god of war

**Comment by Azerrs** [comment]
CJNV-086558 = HLE Emulation Failure
XPWQ-927464 = Damaged Disc
ETYZ-700432 = Corrupted Files
